# Generated by Django 4.2.4 on 2023-08-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_customuser_is_verified_customuser_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='login_date',
            field=models.CharField(blank=True, max_length=19),
        ),
    ]
