# Generated by Django 4.2.4 on 2023-08-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_customuser_login_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='login_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
